### ISSUE TITLE
Will this project keep going? 

### ISSUE THREAD

**Issue by devjoe** [dmnd/socrates#2]
Dear @dmnd,

I've found Khan forked this project and developed it for a short time.  I also played their interactive videos last year several times, but I can't find them on the website anymore these days.

I want to know whether "Socrates" keeps going and why. Could you help me?

> Maybe I should ask this question in Khan's project, but there is no 'Issue' page.
> Sorry to bother you.

**Comment by dmnd** [comment]
Thanks for the question. I no longer work at Khan Academy, so my information might be out of date.

Interactive videos didn't seem to help with engagement, and they harder to create, so as far as I know there is no effort to create new ones or even maintain the old ones. Sorry about that.

**Comment by devjoe** [comment]
Thanks for your kind reply. We (Junyi Academy) will send an official email to ask Khan Academy soon because we are going to implement (enable) this function on our [website](junyiacademy.org).
